{% set version = "2.72.1.53" %}

package:
  name: newrelic
  version: {{ version }}

source:
  fn: newrelic-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/n/newrelic/newrelic-{{ version }}.tar.gz
  sha256: 3f601b32d850d8d56c24756706033ca5e3e3c83520151f5cab37d8a07acaaba2

build:
  number: 1
  script:
    - python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - libtool  # [unix]
    - python
    - setuptools
    - toolchain
  run:
    - python
    - setuptools

test:
  requires:
    - python
  imports:
    - newrelic
  commands:
    - newrelic-admin help  # [unix]

about:
  home: http://newrelic.com/docs/python/new-relic-for-python
  license: New Relic License
  license_file: newrelic/LICENSE  # [unix]
  license_file: newrelic\LICENSE  # [win]
  summary: New Relic Python Agent

extra:
  recipe-maintainers:
    - bollwyvl
