travis:
  secure:
    BINSTAR_TOKEN: HNtYK7Pwsw7vxsVP9+s25pAOCTJXjTwfiR6LSIZJbWqEgjAngVL7ydsxjtFcqzN83myqDXA3NOdyulkFry+++ETfP17VMHwNr7Gfd+6wns9QHk1q6tCpDWOvsLNcJPuR+hQQohU30Dqu2j/aGkHiQKqUwbhZJ3BZ0oBZo7eQJB8tQJp6KCXMSO/bC65gxb+cy0NZwGIEvv8MvrmgpO/J4QqX0Bi+eHNDRi4VJ+9s6RYrU4T5KHdLvr/PLjO24czWBt3XNrGPrO8LaLuQScvgt1F6Qr9+pM/wT442XOKAOl0xQ+4cSX4068A/3+HGztWQciNOQOMjJQB7QjmPpI+mAKz2+Mmaj06LwPKNYvuwuYSkRAbfnbMsv6xgVYE7VC1wVOl4phVJiLdPOSiWQIBXtCogqWWV3e1zGSpriEeh2s0ZfiDKqUw3e6fTTaccN4IvMM8BMwqjV8Euw7tsNtQQMeFwui+Vxl5wtPipgS0x65tWGHJo9iVyH1jI6YFRcHYTXPqlbKmrxT/G9lOZim68WvbxoTf7y6//elL9BjgZXbhhzbWE/zZk6OxGiXUfIHquLqbLtE2I8+CYTD/1IqtjDK2+SXnN8qL38teVSa/C7DfmXvrEfe0msnYlKsglZ0aWuXSfqmzQ+T3YBFsdZ81867dl5noxDa9o7+hz+UB1viY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
